/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_szaoto_ak10_commsdk_Packager */

#ifndef _Included_com_szaoto_ak10_commsdk_Packager
#define _Included_com_szaoto_ak10_commsdk_Packager
#ifdef __cplusplus
extern "C" {
#endif
#undef com_szaoto_ak10_commsdk_Packager_MONITORTYPE_COSTOM
#define com_szaoto_ak10_commsdk_Packager_MONITORTYPE_COSTOM 0L
#undef com_szaoto_ak10_commsdk_Packager_MONITORTYPE_POWER
#define com_szaoto_ak10_commsdk_Packager_MONITORTYPE_POWER 1L
#undef com_szaoto_ak10_commsdk_Packager_MONITORTYPE_POINTDETECT
#define com_szaoto_ak10_commsdk_Packager_MONITORTYPE_POINTDETECT 2L
#undef com_szaoto_ak10_commsdk_Packager_MONITORTYPE_VOTAGE
#define com_szaoto_ak10_commsdk_Packager_MONITORTYPE_VOTAGE 3L
#undef com_szaoto_ak10_commsdk_Packager_MONITORTYPE_WEBERROR
#define com_szaoto_ak10_commsdk_Packager_MONITORTYPE_WEBERROR 4L
#undef com_szaoto_ak10_commsdk_Packager_MONITORACTIONTYPE_FF
#define com_szaoto_ak10_commsdk_Packager_MONITORACTIONTYPE_FF 1L
#undef com_szaoto_ak10_commsdk_Packager_MONITORACTIONTYPE_NORMAL
#define com_szaoto_ak10_commsdk_Packager_MONITORACTIONTYPE_NORMAL 0L
/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    EthernetPackDataBase
 * Signature: ([BLcom/szaoto/ak10/commsdk/FrameDataField;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_EthernetPackDataBase
  (JNIEnv *, jclass, jbyteArray, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    EthernetPackDataWrite
 * Signature: ([B[BII[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_EthernetPackDataWrite
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint, jbyteArray);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    EthernetPackDataRead
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_EthernetPackDataRead
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    EthernetUnPackDataRead
 * Signature: ([BI)Lcom/szaoto/ak10/commsdk/FrameDataField;
 */
JNIEXPORT jobject JNICALL Java_com_szaoto_ak10_commsdk_Packager_EthernetUnPackDataRead
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    NativePackDataBase
 * Signature: (IBII[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_NativePackDataBase
  (JNIEnv *, jclass, jint, jbyte, jint, jint, jbyteArray);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackSetBright
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackSetBright
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackSet3DPara
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackSet3DPara
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);


/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackSetColorTemperature
 * Signature: ([B[BLcom/szaoto/ak10/common/Display/ColourRGB;SS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackSetColorTemperature
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jshort, jshort);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackColorTempCurrentData
 * Signature: ([B[BILcom/szaoto/ak10/common/Display/ColourRGB;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackColorTempCurrentData
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackSetGamma
 * Signature: ([B[BLcom/szaoto/ak10/common/GammaData;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackSetGamma
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackGammaTable
 * Signature: (SLcom/szaoto/ak10/common/GammaData;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackGammaTable
  (JNIEnv *, jclass, jshort, jobject, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackScanCardData
 * Signature: (IILcom/szaoto/ak10/common/CabinetData/CStructSingleScanCard;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackScanCardData
  (JNIEnv *, jclass, jint, jint, jobject, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackStartOrEnd
 * Signature: ([B[BIZSSS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackStartOrEnd
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jboolean, jshort, jshort, jshort);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackHUBPara
 * Signature: (ILcom/szaoto/ak10/common/CabinetData/CStructSingleScanCard;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackHUBPara
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackHUBLookup
 * Signature: (ILcom/szaoto/ak10/common/CabinetData/LinkTable;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackHUBLookup
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackScanCardUpdateStart
 * Signature: ([B[BISZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackScanCardUpdateStart
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jshort, jboolean, jboolean);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackSaveScanCardPara
 * Signature: ([B[BSIZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackSaveScanCardPara
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jint, jboolean);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackScanCardLoadRegionData
 * Signature: (SLcom/szaoto/ak10/common/RECT;SS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackScanCardLoadRegionData
  (JNIEnv *, jclass, jshort, jobject, jshort, jshort);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    Pack6ScanCardData
 * Signature: ([B[BILcom/szaoto/ak10/common/CabinetData/CStructSingleScanCard;Lcom/szaoto/ak10/common/CabinetData/Drive_ic_reg;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_Pack6ScanCardData
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jobject, jobject, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackNoSingleDisp
 * Signature: (SS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackNoSingleDisp
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackOperationProcessing
 * Signature: (SS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackOperationProcessing
  (JNIEnv *, jclass, jshort, jshort);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackVideoProcessing
 * Signature: (SLcom/szaoto/ak10/common/CabinetData/CStructSingleScanCard;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackVideoProcessing
  (JNIEnv *, jclass, jshort, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackCorrectProcessing
 * Signature: (SLcom/szaoto/ak10/common/CabinetData/CStructSingleScanCard;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackCorrectProcessing
  (JNIEnv *, jclass, jshort, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackCorrectProcessingLookup
 * Signature: (SLcom/szaoto/ak10/common/CabinetData/CStructSingleScanCard;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackCorrectProcessingLookup
  (JNIEnv *, jclass, jshort, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackScanCardLinkTable
 * Signature: (SSSLcom/szaoto/ak10/common/CabinetData/LinkTable;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackScanCardLinkTable
  (JNIEnv *, jclass, jshort, jshort, jshort, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackScanCardSectionLinkTable
 * Signature: (SLcom/szaoto/ak10/common/CabinetData/LinkTable;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackScanCardSectionLinkTable
  (JNIEnv *, jclass, jshort, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackCalibrationEnable
 * Signature: (SZS)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackCalibrationEnable
  (JNIEnv *, jclass, jshort, jboolean, jshort);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackLockUnlock
 * Signature: ([B[BSZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackLockUnlock
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jboolean);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackScanCardIntelligentPara
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackScanCardIntelligentPara
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackRelay
 * Signature: ([B[BSSZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackRelay
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jshort, jboolean);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackRelayAttribute
 * Signature: ([B[BSSZZZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackRelayAttribute
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jshort, jboolean, jboolean, jboolean);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackRelayThreshold
 * Signature: ([B[BSSFFFF)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackRelayThreshold
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jshort, jshort, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackOpenCabinetLamps
 * Signature: (SZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackOpenCabinetLamps
  (JNIEnv *, jclass, jshort, jboolean);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    test
 * Signature: ()Lcom/szaoto/ak10/common/MonitorData;
 */
JNIEXPORT jobject JNICALL Java_com_szaoto_ak10_commsdk_Packager_test
  (JNIEnv *, jclass);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackMonitorData
 * Signature: (II[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackMonitorData
  (JNIEnv *, jclass, jint, jint, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackMonitorConnectstate
 * Signature: ([B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackMonitorConnectstate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackAcquiAcquisitionCardEdidInfor
 * Signature: ([B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackAcquiAcquisitionCardEdidInfor
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    UnPack28Data
 * Signature: ([BS)I
 */
JNIEXPORT jint JNICALL Java_com_szaoto_ak10_commsdk_Packager_UnPack28Data
  (JNIEnv *, jclass, jbyteArray, jshort);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    UnPackCustomMonitorData
 * Signature: ([B[BLcom/szaoto/ak10/common/MonitorData;)Lcom/szaoto/ak10/common/MonitorData;
 */
JNIEXPORT jobject JNICALL Java_com_szaoto_ak10_commsdk_Packager_UnPackCustomMonitorData
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    UnPackPowerMonitorData
 * Signature: ([B[BLcom/szaoto/ak10/common/MonitorData;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_UnPackPowerMonitorData
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    UnPackPointDetectMonitorData
 * Signature: ([B[BLcom/szaoto/ak10/common/MonitorData;Lcom/szaoto/ak10/common/CabinetData/ScanCardAttachment;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_UnPackPointDetectMonitorData
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    UnPackNetWebErrorPackage
 * Signature: ([B[BLcom/szaoto/ak10/common/MonitorData;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_UnPackNetWebErrorPackage
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    UnPackMonitorDataFunRate
 * Signature: ([B[BLcom/szaoto/ak10/common/MonitorData;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_UnPackMonitorDataFunRate
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jobject);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    PackMutiple28byteData
 * Signature: ([B[B[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_szaoto_ak10_commsdk_Packager_PackMutiple28byteData
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jint);

/*
 * Class:     com_szaoto_ak10_commsdk_Packager
 * Method:    getlasterror
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_szaoto_ak10_commsdk_Packager_getlasterror
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
